pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "check-success=eslint"
      - "check-success=tests"
    actions:
      merge:
        strict: "smart"
        method: squash
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflict 😕
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: dismiss reviews
    conditions:
      - author!=@react-crisp
    actions:
      dismiss_reviews: {}
  - name: dismiss reviews for core devs
    conditions:
      - author=@react-crisp
    actions:
      dismiss_reviews:
        # Do not remove approval for core devs
        approved: false
  - name: request review
    conditions:
      - -merged
      - -closed
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "check-success=eslint"
      - "check-success=tests"
    actions:
      request_reviews:
        teams:
          - react-crisp
