pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
      - label!=manual merge
      - "check-success=lintSrc (10.x)"
      - "check-success=lintSrc (12.x)"
      - "check-success=lintSrc (14.x)"
    actions:
      merge:
        strict: "smart"
        method: rebase
  - name: automatic merge from dependabot
    conditions:
      - author=dependabot[bot]
      - label!=work-in-progress
      - label!=manual merge
      - "check-success=lintSrc (10.x)"
      - "check-success=lintSrc (12.x)"
      - "check-success=lintSrc (14.x)"
    actions:
      merge:
        strict: "smart"
        method: rebase
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflict 😕
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
  - name: dismiss reviews
    conditions:
      - author!=@devs
    actions:
      dismiss_reviews: {}
  - name: dismiss reviews for core devs
    conditions:
      - author=@devs
    actions:
      dismiss_reviews:
        # Do not remove approval for core devs
        approved: false
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - label!=work-in-progress
      - label!=no-review-needed
      - -merged
      - -closed
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "check-success=lintSrc (10.x)"
      - "check-success=lintSrc (12.x)"
      - "check-success=lintSrc (14.x)"
    actions:
      request_reviews:
        teams:
          - devs
  - name: auto add wip
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ["work-in-progress"]